dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages: 
    - doxygen
    - graphviz

script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujacksonrr3:$BINTRAY_API_KEY "https://api.bintray.com/content/jacksonrr3/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
